apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-deployment
  namespace: smart-lighting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decision
  template:
    metadata:
      labels:
        app: decision
    spec:
      containers:
      - name: decision
        image: smart-lighting-decision-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: configmap-decision
        - secretRef:
            name: secret-decision
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"