apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-deployment
  namespace: smart-lighting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging
        image: smart-lighting-logging-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: configmap-logging
        - secretRef:
            name: secret-logging
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"