apiVersion: v1
kind: Service
metadata:
  name: decision-service
  namespace: smart-lighting
spec:
  type: NodePort
  selector:
    app: decision
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001