apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: smart-lighting
spec:
  type: NodePort
  selector:
    app: logging
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002