apiVersion: v1
kind: Service
metadata:
  name: override-service
  namespace: smart-lighting
spec:
  type: NodePort
  selector:
    app: override
  ports:
  - port: 3003
    targetPort: 3003
    nodePort: 30003