apiVersion: v1
kind: Service
metadata:
  name: sensor-simulator-service
  namespace: smart-lighting
spec:
  type: ClusterIP
  selector:
    app: sensor-simulator
  ports:
  - port: 8080
    targetPort: 8080